#!/usr/bin/python3

import argparse
import logging
import os.path
import pathlib
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

from show_page.browser import BrowserView

if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='Open web page in Keyman browser window')
  parser.add_argument('-f', '--file', action='store', help='page to open')
  parser.add_argument('-n', '--name', action='store', help='Keyboard name')
  parser.add_argument('--close', action='store_true', help='Autoclose dialog')

  args = parser.parse_args()

  if args.file and args.name:
    logging.info("Open %s if available", args.file)
    if args.file and os.path.isfile(args.file):
      uri_path = pathlib.Path(os.path.abspath(args.file)).as_uri()
      logging.info("opening " + uri_path)
      w = BrowserView(uri_path, args.name, args.close)
      w.resize(800, 600)
      w.connect("destroy", Gtk.main_quit)
      w.show_all()
      Gtk.main()
    else:
      logging.info("%s not available", args.file)
      print(args.file + " is not available")
  else:
    print("No file specified")
